exp: TextClassification
mode: 
    - evaluate

model: ../trainedModel

datafpath: ../data/evaluate_dataset.tsv

predfpath: ../data/predictions.tsv

giveAllLabels: true

id2label:
  0: Paul
  1: Peter
  2: John
  3: James
  4: Jude
  5: Luke
  6: Matthew
  7: Mark

max_length: 128
batch_size: 64
