exp: TextClassification
mode: 
  - train

models: 
  hf_text_classification_model:
        - distilbert-base-uncased           

trainfpath:   ../BibleClassify/data/train_dataset.tsv
validfpath:   ../BibleClassify/data/validate_dataset.tsv
modelfpath: ../BibleClassify/trainedModel

id2label:
  0: Paul
  1: Peter
  2: John
  3: James
  4: Jude
  5: Luke
  6: Matthew
  7: Mark


loadPretrained: true

numLabels: 8