exp: TextClassification
mode: 
  - evaluate

models: 
  hf_text_classification_model:
      - ../trainedModel

datafpath: ../BibleClassify/data/verify_dataset.tsv

predfpath: ../BibleClassify/data/predictions_verify.tsv

giveAllLabels: true

id2label:
  0: Paul
  1: Peter
  2: John
  3: James
  4: Jude
  5: Luke
  6: Matthew
  7: Mark


